### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by Kerodas** [naruto-unison/naruto-unison#3] opened 2019-07-22 08:15 UTC
1. With the latest build, Quick Battle doesn't work.

2. Percentage damage reduction doesn't work as intended. For example Kurotsuchi's skill called "Lava Quicklime" is supposed to give 50% damage reduction for 1 turn, instead it gives 50 damage reduction.

3. As you suggested, I tried changing practice team through Select.elm, but it doesn't seem to work.  I also tried rebuilding after making a change, but it's no use.

**Comment by jnbooth** [comment] 2019-07-25 07:25
Yes, lots of things do not currently work as intended, including:

- Private Matches are unimplemented
- Matchmaking for Quick Battles is rudimentary at best
- Barriers are very limited while I try to figure out if there is a better way than using ImpredicativeTypes
- Less than half of the characters have been added
- There is no missions system

All of which is because this is a hobby project at present. It could be as long as a year before alpha. Then, and only then, will I tell people about N-U, post it on subreddits, etc. That will also be the point at which I try to recruit other people so it's a team project and not just my thing. Until then, not even the documentation is guaranteed to be reliable.

The main reason this repository is public is that the person who does most of the character designs doesn't have a GitHub account. If others happen to stumble upon it and want to play around with it, that's great, and I try to keep that in mind with my commits now that I know people are doing it, but I do not guarantee that the code will be in any way stable or functional. Just last month, I converted the entire frontend from PureScript to Elm because PureScript felt sluggish and Elm is very fast. If PureScript improves its performance, I might switch everything back again. Nothing is set in stone.

Well, except Haskell. Because I like Haskell.

Anyway, none of this is meant to be brusque or discouraging. I will check all of those out, and I certainly won't close this issue until they are fixed. It just seemed like it might be a good idea to clarify the current state of the project. I've put a little disclaimer in the README, too.

**Comment by Kerodas** [comment] 2019-07-25 08:23
Don't worry, I know that the project is far from complete, I am just pointing out some issues I've discovered after playing around with the project for a while. 
If this would help in any way, I could contribute by coding characters, since based on the templates, I've already made some old n-a characters like old n-a Chouji for example, as well as add all old n-a and s-a characters as an optional thing.
Thank you!

**Comment by jnbooth** [comment] 2019-07-25 23:00
There is now a menu to choose opponents during practice, so that addresses part 3. Keep in mind that Elm code is compiled separately from Haskell code; the command to compile it is `(cd elm && npm install)`.

Actually, there is something you could do if you wanted to get your feet wet. I have a basic testing framework in [/test/TestImport.hs](/test/TestImport.hs), and an example at [/test/Characters/Original/KidsSpec.hs](/test/Characters/Original/KidsSpec.hs). It would be extremely helpful for someone to go through the characters already in the database and add specs for them. The idea is for the directory structure to mirror that of [/src/Characters/], with "Spec" added to the end of each filename.

You could try writing specs for a few characters, see how it goes, and submit them as a pull request. If a test fails, don't worry about it—that's my problem to solve. The point is to get a framework in place so that eventually, adding a spec will be the first step of creating a new character. I don't know if that would be of interest to you, but it would certainly be helpful.

**Comment by jnbooth** [comment] 2019-07-25 23:02
There is now a menu to choose opponents during practice, so that addresses part 3. Keep in mind that Elm code is compiled separately from Haskell code; the command to compile it is `(cd elm && npm install)`.

Actually, there is something you could do if you wanted to get your feet wet. I have a basic testing framework in [/test/TestImport.hs](https://github.com/naruto-unison/naruto-unison/blob/master/test/TestImport.hs), and an example at [/test/Characters/Original/KidsSpec.hs](https://github.com/naruto-unison/naruto-unison/blob/master/test/Characters/Original/KidsSpec.hs). It would be extremely helpful for someone to go through the characters already in the database and add specs for them. The idea is for the directory structure to mirror that of [/src/Characters/](https://github.com/naruto-unison/naruto-unison/tree/master/src/Characters), with "Spec" added to the end of each filename.

You could try writing specs for a few characters, see how it goes, and submit them as a pull request. If a test fails, don't worry about it—that's my problem to solve. The point is to get a framework in place so that eventually, adding a spec will be the first step of creating a new character. I don't know if that would be of interest to you, but it would certainly be helpful.

**Comment by jnbooth** [comment] 2019-07-25 23:03
There is now a menu to choose opponents during practice, so that addresses part 3. It's very basic in appearance until I figure out a clean layout for those elements. Keep in mind that Elm code is compiled separately from Haskell code; the command to compile it is `(cd elm && npm install)`.

Actually, there is something you could do if you wanted to get your feet wet. I have a basic testing framework in [/test/TestImport.hs](https://github.com/naruto-unison/naruto-unison/blob/master/test/TestImport.hs), and an example at [/test/Characters/Original/KidsSpec.hs](https://github.com/naruto-unison/naruto-unison/blob/master/test/Characters/Original/KidsSpec.hs). It would be extremely helpful for someone to go through the characters already in the database and add specs for them. The idea is for the directory structure to mirror that of [/src/Characters/](https://github.com/naruto-unison/naruto-unison/tree/master/src/Characters), with "Spec" added to the end of each filename.

You could try writing specs for a few characters, see how it goes, and submit them as a pull request. If a test fails, don't worry about it—that's my problem to solve. The point is to get a framework in place so that eventually, adding a spec will be the first step of creating a new character. I don't know if that would be of interest to you, but it would certainly be helpful.

**Comment by jnbooth** [comment] 2019-07-25 23:14
Oh, and see if recompiling your Elm makes Quick Matches work again. I updated the JS code that invokes Elm a few commits ago in order to match changes in Elm. If the two were out of sync, it might cause an error that would get in the way of the websockets layer.

**Closed** 2019-07-25 23:23 UTC

**Comment by jnbooth** [comment] 2019-07-25 23:24
Percentage damage reduction should now be fixed.
